include:
  remote: 'https://gitlab.com/openetymologymap/osm-wikidata-map-framework/-/raw/main/common.gitlab-ci.yml'

variables:
  SENTRY_RELEASE_NAME: "open-etymology-map-$CI_COMMIT_TAG"

stages:
  - release

gitlab_release:
  extends: .gitlab_release

sentry_release:
  extends: .sentry_release
