version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    image: dsantini/openetymologymap:dev
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./open-etymology-map.ini:/etc/open-etymology-map.ini
      - ./open-etymology-map.log:/var/log/open-etymology-map.log
      - ./open-etymology-map-cache:/tmp/open-etymology-map-cache
