# https://www.sumologic.com/blog/kubernetes-deploy-postgres/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oem-db-volume
  labels:
    app: oem-db
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
