apiVersion: v1
kind: Service
metadata:
  name: oem-web-http-service
  labels:
    app: oem-web
spec:
  type: NodePort
  selector:
    app: oem-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
