apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oem-db
  labels:
    app: oem-db
spec:
  selector:
    matchLabels:
      app: oem-db
  serviceName: oem-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: oem-db
    spec:
      containers:
      - name: oem-db
        #image: postgis/postgis:13-3.2-alpine #arm64 currently not supported, TODO check https://github.com/postgis/docker-postgis/issues/216
        image: odidev/postgis:13-3.1-alpine
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: oem-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: oem-db-data
          persistentVolumeClaim:
            claimName: oem-db-volume-claim
