apiVersion: v1
kind: Service
metadata:
  name: oem-db-service
  labels:
    app: oem-db
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30432
  selector:
    app: oem-db
