apiVersion: v1
kind: PersistentVolume
metadata:
  name: oem-ini
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: open-etymology-map.ini
