apiVersion: v1
kind: Service
metadata:
  name: oem-web-https-service
  labels:
    app: oem-web
spec:
  type: NodePort
  selector:
    app: oem-web
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
