apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oem-db-volume-claim
  labels:
    app: oem-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
